### ISSUE TITLE
Crashes with white screen. 【OLD3DS JP】

### ISSUE THREAD

**Issue by KeiChannel-2552** [zoogie/Kartminer7#17]
Hello.
I am looking to run kartminer7 using a Japanese OLD3DS.

Unfortunately, after pressing OK the Mario Kart race starts.
I get a white screen and it says "The software was forcibly terminated due to an error. We will restart." message appears and I am unable to proceed.

I have tried repeating the same action about 20 times and it crashes the same way.

I searched YouTube to see if there were others in the same boat and found a comment that JPOLD3DS could not do it.

I hope you can fix the program.
I am always impressed by your work.

![スクリーンショット 2023-08-16 182424](https://github.com/zoogie/Kartminer7/assets/110430611/a6a1aa30-ef24-4e38-a48e-a6fe66ab0f4f)
![スクリーンショット 2023-08-16 182446](https://github.com/zoogie/Kartminer7/assets/110430611/42319c78-c3b3-4b8b-8e49-02d186ddf4ca)
![スクリーンショット 2023-08-16 182503](https://github.com/zoogie/Kartminer7/assets/110430611/8c20fd7d-2b71-4a24-81ef-78de482784a0)

**Comment by Fortheart** [comment]
I've got the same issue with the old jpn 3DS. On the japanese version there is not an option to change the language so there is no way of passing the race start screen.

**Comment by zoogie** [comment]
The last hope for issues like this rests in this one issue: https://github.com/zoogie/Kartminer7/issues/16

The reason is: I cannot debug your issues because they do not occur on my <insert region/model 3ds here> and thus I completely rely on people, with cfw, that already have your exact problem and can give me crash dumps.

Given that people have nothing to gain personally after they get their cfw, there isn't much hope in them replying to that thread.
